language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.0
env:
  - RAILS_VERSION="~> 4.2.0"

before_install:
  - gem install bundler -v 1.11.0
  - bundler version
before_script:
  - travis_retry gem install rails --version "$RAILS_VERSION"
